import { Router } from "express";
import DaftarGaji from "./DaftarGaji";
import DataCetak from "./DataCetak";
import DataNomor from "./DataNomor";
import DataSptPegawai from "./DataSptPegawai";
import FilePreview from "./FilePreview";
import Form1721A2 from "./Form1721A2";
import Form1721VII from "./Form1721VII";
import Gaji from "./Gaji";
import KP4 from "./KP4";
import KekuranganGaji from "./KekuranganGaji";
import KekuranganTukin from "./KekuranganTukin";
import Penghasilan from "./Penghasilan";
import PenghasilanLain from "./PenghasilanLain";
import Profil from "./Profil";
import RefJabatan from "./RefJabatan";
import RefPangkat from "./RefPangkat";
import RefSatker from "./RefSatker";
import RefSptTahunan from "./RefSptTahunan";
import Skp from "./Skp";
import Tukin from "./Tukin";
import UangLembur from "./UangLembur";
import UangMakan from "./UangMakan";

const router = Router();

router.use("/DataCetak", DataCetak);
router.use("/1721-A2", Form1721A2);
router.use("/1721-VII", Form1721VII);
router.use("/DaftarGaji", DaftarGaji);
router.use("/DataNomor", DataNomor);
router.use("/DataSptPegawai", DataSptPegawai);
router.use("/FilePreview", FilePreview);
router.use("/Gaji", Gaji);
router.use("/KekuranganGaji", KekuranganGaji);
router.use("/Tukin", Tukin);
router.use("/KekuranganTukin", KekuranganTukin);
router.use("/KP4", KP4);
router.use("/PenghasilanLain", PenghasilanLain);
router.use("/Profil", Profil);
router.use("/RefJabatan", RefJabatan);
router.use("/RefSatker", RefSatker);
router.use("/RefPangkat", RefPangkat);
router.use("/RefSptTahunan", RefSptTahunan);
router.use("/Skp", Skp);
router.use("/UangLembur", UangLembur);
router.use("/UangMakan", UangMakan);
router.use("/Penghasilan", Penghasilan);

export default router;
