export interface Keluarga {
  IdpegawaiKeluarga: number;
  IdrefValiditas: number;
  IdrefStatusData: number | null;
  CreatedDate: string;
  CreatedBy: 141840;
  Lampiran: string | null;
  AktaCerai: string | null;
  TanggalCerai: string | null;
  AktaNikah: string | null;
  TanggalMenikah: string | null;
  TempatLahir: string;
  TanggalLahir: string;
  Nama: string;
  IdrefStatusMenikah: number;
  StatusMenikah: string;
  IdrefHubungan: number;
  Hubungan: string;
  JenisKelamin: string;
  StatusTanggungan: string;
  Idpegawai: 141840;
  Idlama: number | null;
  IdrefStatusHidupKeluarga: string;
  IdrefPekerjaan: number;
  Pekerjaan: string;
  Esl1: string;
  UraianStatusValiditas: string;
}

export interface Profile {
  Idpegawai: number;
  Nip9: string;
  Nip18: string;
  Nik: string;
  Nama: string;
  KodeGolongan: string;
  KodeGolonganRuang: string;
  Jabatan: string;
  JenisJabatan: string;
  StatusPegawai: string;
  GelarDepan: string;
  GelarBelakang: string;
  Esl1: string;
  Esl2: string;
  Esl3: string;
  Esl4: string;
  Esl5: string;
  KdSatker: string;
  NamaSatker: string;
  TempatLahir: string;
  TanggalLahir: string;
  JenisKelamin: string;
  Agama: string;
  GolonganDarah: string;
  NoKartuPegawai: string;
  Npwp: string;
  AlamatKtp: string;
  KotaKtp: string;
  ProvinsiKtp: string;
  KodePosKtp: string;
  AlamatDomisili: string;
  KotaDomisili: string;
  ProvinsiDomisili: string;
  KodePosDomisili: string;
  NomorTelepon: string;
  Email: string;
  NoHp: string;
  NoKk: string;
  NamaKontakDarurat: string;
  NomorKontakDarurat: string;
  KodeOrganisasi: string;
  KodeIndukOrganisasi: string;
  Organisasi: string;
  Grading: number;
  IDRefJenisTugasBelajar: string;
  JenisTugasBelajar: string;
  IsPerpanjanganTB: boolean;
  TMTStatusPegawai: string;
  TanggalSKStatusPegawai: string;
}
